// AUTO-GENERATED by boardsmith build-ai
// Do not edit manually - regenerate with: npx boardsmith build-ai
//
// Training Statistics:
//   Games played: 1
//   Games completed: 1
//   Total states analyzed: 58
//   Candidate features: 38
//   Features selected: 4
//   Training iterations: 1
//   Estimated win rate vs random: 57.7%

import type { Game } from '@boardsmith/engine';
import type { Objective } from '@boardsmith/ai';
import type { GoFishGame } from './game.js';

/**
 * Action Preferences (learned from self-play):
 *   ask: +0.9 (prefer)
 */

/**
 * AI objectives for GoFish
 * These guide the MCTS bot to prefer better positions during playouts
 * 
 * Generated through self-play simulation and statistical analysis.
 * Higher weight = more important for winning.
 */
export function getGoFishObjectives(
  game: Game,
  playerIndex: number
): Record<string, Objective> {
  const goFishGame = game as GoFishGame;
  const player = goFishGame.players[playerIndex] as Player;
  const opponent = goFishGame.players[1 - playerIndex] as Player;

  return {
    // Player has higher bookCount than opponent
    // Correlation: +0.416
    'player-bookCount-lead': {
      checker: () => player.bookCount > opponent.bookCount,
      weight: 4.2,
    },

    // Player bookCount is at least 5
    // Correlation: +0.383
    'player-bookCount-gte-5': {
      checker: () => player.bookCount >= 5,
      weight: 3.8,
    },

    // Player bookCount is at least 10
    // Correlation: +0.111
    'player-bookCount-gte-10': {
      checker: () => player.bookCount >= 10,
      weight: 1.1,
    },

    // Player bookCount is very high (near win)
    // Correlation: +0.111
    'player-bookCount-near-max': {
      checker: () => {
        const maxScore = Math.max(...goFishGame.players.map(p => p.bookCount ?? 0));
        return maxScore > 0 && player.bookCount >= maxScore * 0.75;
      },
      weight: 1.1,
    }

  };
}
