import type {
  TrainingResult,
  LearnedObjective,
  GameStructure,
  CandidateFeature,
} from './types.js';

/**
 * Options for code generation
 */
export interface CodeGeneratorOptions {
  /** Game class name (e.g., 'GoFishGame') */
  gameClassName: string;
  /** Player class name (e.g., 'GoFishPlayer') */
  playerClassName?: string;
  /** Include comments with training metadata */
  includeMetadata: boolean;
  /** Include action preferences as comments */
  includeActionHints: boolean;
  /** Game structure (for better code generation) */
  structure?: GameStructure;
  /** Original candidate features (for code generation) */
  features?: CandidateFeature[];
}

/**
 * Generate an ai.ts file from training results
 */
export function generateAICode(
  result: TrainingResult,
  options: CodeGeneratorOptions
): string {
  const lines: string[] = [];

  // Header
  lines.push(`// AUTO-GENERATED by boardsmith build-ai`);
  lines.push(`// Do not edit manually - regenerate with: npx boardsmith build-ai`);

  if (options.includeMetadata) {
    lines.push(`//`);
    lines.push(`// Training Statistics:`);
    lines.push(`//   Games played: ${result.metadata.gamesPlayed}`);
    lines.push(`//   Games completed: ${result.metadata.gamesCompleted}`);
    lines.push(`//   Total states analyzed: ${result.metadata.totalStates}`);
    lines.push(`//   Candidate features: ${result.metadata.candidateFeaturesGenerated}`);
    lines.push(`//   Features selected: ${result.metadata.featuresSelected}`);
    lines.push(`//   Training iterations: ${result.metadata.iterations}`);
    lines.push(`//   Estimated win rate vs random: ${(result.metadata.finalWinRate * 100).toFixed(1)}%`);
  }

  lines.push(``);

  // Imports
  lines.push(`import type { Game } from '@boardsmith/engine';`);
  lines.push(`import type { Objective } from '@boardsmith/ai';`);

  // Import game-specific types if provided
  if (options.gameClassName) {
    const imports = [`${options.gameClassName}`];
    if (options.playerClassName) {
      imports.push(options.playerClassName);
    }
    lines.push(`import type { ${imports.join(', ')} } from './game.js';`);
  }

  // Import element types if we have structure info
  if (options.structure) {
    const elementImports = getRequiredElementImports(result.objectives, options.structure);
    if (elementImports.length > 0) {
      lines.push(`import { ${elementImports.join(', ')} } from './elements.js';`);
    }
  }

  lines.push(``);

  // Action hints as comments
  if (options.includeActionHints && result.actionPreferences.length > 0) {
    lines.push(`/**`);
    lines.push(` * Action Preferences (learned from self-play):`);
    for (const pref of result.actionPreferences.slice(0, 5)) {
      const sign = pref.weight > 0 ? '+' : '';
      lines.push(` *   ${pref.actionName}: ${sign}${pref.weight.toFixed(1)} (${pref.weight > 0 ? 'prefer' : 'avoid'})`);
    }
    lines.push(` */`);
    lines.push(``);
  }

  // Main objectives function
  const funcName = `get${options.gameClassName.replace('Game', '')}Objectives`;
  const playerType = options.playerClassName || 'Player';

  lines.push(`/**`);
  lines.push(` * AI objectives for ${options.gameClassName.replace('Game', '')}`);
  lines.push(` * These guide the MCTS bot to prefer better positions during playouts`);
  lines.push(` * `);
  lines.push(` * Generated through self-play simulation and statistical analysis.`);
  lines.push(` * Higher weight = more important for winning.`);
  lines.push(` */`);
  lines.push(`export function ${funcName}(`);
  lines.push(`  game: Game,`);
  lines.push(`  playerIndex: number`);
  lines.push(`): Record<string, Objective> {`);

  // Game and player setup
  lines.push(`  const ${camelCase(options.gameClassName)} = game as ${options.gameClassName};`);
  lines.push(`  const player = ${camelCase(options.gameClassName)}.players[playerIndex] as ${playerType};`);

  // Only add opponent if we have 2-player objectives
  const needs2Player = result.objectives.some(o =>
    o.description.includes('opponent') ||
    o.description.includes('than opponent') ||
    o.featureId.includes('advantage') ||
    o.featureId.includes('lead')
  );
  if (needs2Player) {
    lines.push(`  const opponent = ${camelCase(options.gameClassName)}.players[1 - playerIndex] as ${playerType};`);
  }

  lines.push(``);
  lines.push(`  return {`);

  // Generate each objective
  for (let i = 0; i < result.objectives.length; i++) {
    const obj = result.objectives[i];
    const isLast = i === result.objectives.length - 1;

    lines.push(`    // ${obj.description}`);
    lines.push(`    // Correlation: ${obj.correlation > 0 ? '+' : ''}${obj.correlation.toFixed(3)}`);
    lines.push(`    '${obj.featureId}': {`);
    lines.push(`      checker: ${generateCheckerFunction(obj, options)},`);
    lines.push(`      weight: ${obj.weight},`);
    lines.push(`    }${isLast ? '' : ','}`);
    lines.push(``);
  }

  lines.push(`  };`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Generate a checker function for an objective
 */
function generateCheckerFunction(
  obj: LearnedObjective,
  options: CodeGeneratorOptions
): string {
  const id = obj.featureId;
  const gameVar = camelCase(options.gameClassName);

  // Parse feature ID to generate appropriate code
  // Format: elementtype-property-comparison or player-property-comparison

  // Element count advantage
  if (id.includes('-count-advantage')) {
    const elementType = capitalize(id.split('-count-advantage')[0]);
    return `() => {
        const myCount = ${gameVar}.all(${elementType}, { player }).length;
        const theirCount = ${gameVar}.all(${elementType}, { player: opponent }).length;
        return myCount > theirCount;
      }`;
  }

  // Element count disadvantage
  if (id.includes('-count-disadvantage')) {
    const elementType = capitalize(id.split('-count-disadvantage')[0]);
    return `() => {
        const myCount = ${gameVar}.all(${elementType}, { player }).length;
        const theirCount = ${gameVar}.all(${elementType}, { player: opponent }).length;
        return myCount < theirCount;
      }`;
  }

  // Element count threshold
  if (id.includes('-count-gte-')) {
    const parts = id.split('-count-gte-');
    const elementType = capitalize(parts[0]);
    const threshold = parts[1];
    return `() => ${gameVar}.all(${elementType}, { player }).length >= ${threshold}`;
  }

  if (id.includes('-count-zero')) {
    const elementType = capitalize(id.split('-count-zero')[0]);
    return `() => ${gameVar}.all(${elementType}, { player }).length === 0`;
  }

  // Boolean property check
  if (id.includes('-has-')) {
    const parts = id.split('-has-');
    const elementType = capitalize(parts[0]);
    const property = parts[1];
    return `() => ${gameVar}.all(${elementType}, { player }).some(e => e.${property})`;
  }

  // Boolean property advantage
  if (id.match(/-\w+-advantage$/)) {
    const parts = id.split('-');
    const elementType = capitalize(parts[0]);
    const property = parts.slice(1, -1).join('-');
    return `() => {
        const myCount = ${gameVar}.all(${elementType}, { player }).filter(e => e.${property}).length;
        const theirCount = ${gameVar}.all(${elementType}, { player: opponent }).filter(e => e.${property}).length;
        return myCount > theirCount;
      }`;
  }

  // Player score lead
  if (id.startsWith('player-') && id.endsWith('-lead')) {
    const property = id.replace('player-', '').replace('-lead', '');
    return `() => player.${property} > opponent.${property}`;
  }

  // Player score threshold
  if (id.startsWith('player-') && id.includes('-gte-')) {
    const parts = id.replace('player-', '').split('-gte-');
    const property = parts[0];
    const threshold = parts[1];
    return `() => player.${property} >= ${threshold}`;
  }

  // Player near-max
  if (id.includes('-near-max')) {
    const property = id.replace('player-', '').replace('-near-max', '');
    return `() => {
        const maxScore = Math.max(...${gameVar}.players.map(p => p.${property} ?? 0));
        return maxScore > 0 && player.${property} >= maxScore * 0.75;
      }`;
  }

  // Spatial: center control
  if (id.includes('-center-control')) {
    const elementType = capitalize(id.split('-center-control')[0]);
    return `() => {
        const elements = ${gameVar}.all(${elementType}, { player });
        return elements.some(e => e.row !== undefined && e.column !== undefined);
      }`;
  }

  // Spatial: center advantage
  if (id.includes('-center-advantage')) {
    const elementType = capitalize(id.split('-center-advantage')[0]);
    return `() => {
        const myCenter = ${gameVar}.all(${elementType}, { player }).filter(e =>
          e.row !== undefined && e.row >= 2 && e.row <= 5
        ).length;
        const theirCenter = ${gameVar}.all(${elementType}, { player: opponent }).filter(e =>
          e.row !== undefined && e.row >= 2 && e.row <= 5
        ).length;
        return myCenter > theirCenter;
      }`;
  }

  // Spatial: advancement
  if (id.includes('-advanced')) {
    const elementType = capitalize(id.split('-advanced')[0]);
    return `() => {
        const elements = ${gameVar}.all(${elementType}, { player });
        if (elements.length === 0) return false;
        const advancedCount = elements.filter(e => {
          if (e.row === undefined) return false;
          return playerIndex === 0 ? e.row > 3 : e.row < 4;
        }).length;
        return advancedCount > elements.length / 2;
      }`;
  }

  // Spatial: back row
  if (id.includes('-back-row')) {
    const elementType = capitalize(id.split('-back-row')[0]);
    return `() => {
        const backRow = playerIndex === 0 ? 0 : 7;
        return ${gameVar}.all(${elementType}, { player }).some(e => e.row === backRow);
      }`;
  }

  // Majority
  if (id.includes('-majority')) {
    const elementType = capitalize(id.split('-majority')[0]);
    return `() => {
        const myCount = ${gameVar}.all(${elementType}, { player }).length;
        const total = ${gameVar}.all(${elementType}).length;
        return total > 0 && myCount > total / 2;
      }`;
  }

  // Dominance
  if (id.includes('-dominance')) {
    const elementType = capitalize(id.split('-dominance')[0]);
    return `() => {
        const myCount = ${gameVar}.all(${elementType}, { player }).length;
        const total = ${gameVar}.all(${elementType}).length;
        return total > 0 && myCount > total * 0.66;
      }`;
  }

  // Sum advantage
  if (id.includes('-sum-advantage')) {
    const parts = id.split('-');
    const elementType = capitalize(parts[0]);
    const property = parts[1];
    return `() => {
        const mySum = ${gameVar}.all(${elementType}, { player }).reduce((s, e) => s + (e.${property} ?? 0), 0);
        const theirSum = ${gameVar}.all(${elementType}, { player: opponent }).reduce((s, e) => s + (e.${property} ?? 0), 0);
        return mySum > theirSum;
      }`;
  }

  // Sum threshold
  if (id.includes('-sum-gte-')) {
    const parts = id.split('-sum-gte-');
    const [elementType, property] = parts[0].split('-');
    const threshold = parts[1];
    return `() => {
        const sum = ${gameVar}.all(${capitalize(elementType)}, { player }).reduce((s, e) => s + (e.${property} ?? 0), 0);
        return sum >= ${threshold};
      }`;
  }

  // String property match
  if (id.match(/^[a-z]+-[a-z]+-[a-z-]+$/)) {
    // Could be elementtype-property-value
    const parts = id.split('-');
    if (parts.length >= 3) {
      const elementType = capitalize(parts[0]);
      const property = parts[1];
      const value = parts.slice(2).join('-');
      return `() => ${gameVar}.all(${elementType}, { player }).some(e => e.${property} === '${value}')`;
    }
  }

  // Default fallback with description as comment
  console.warn(
    `[AI Code Generator] Unknown feature pattern: "${id}". ` +
    `Generated fallback checker that always returns true. ` +
    `Consider implementing custom logic for: ${obj.description}`
  );
  return `() => {
        // ${obj.description}
        // WARNING: Auto-generated fallback - always returns true
        // Implement game-specific logic for better AI performance
        return true;
      }`;
}

/**
 * Get required element type imports
 */
function getRequiredElementImports(
  objectives: LearnedObjective[],
  structure: GameStructure
): string[] {
  const imports = new Set<string>();

  for (const obj of objectives) {
    const id = obj.featureId;

    // Extract element type from feature ID
    for (const [className] of structure.elementTypes) {
      if (id.toLowerCase().startsWith(className.toLowerCase())) {
        imports.add(className);
      }
    }
  }

  return [...imports].sort();
}

/**
 * Convert to camelCase
 */
function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

/**
 * Capitalize first letter
 */
function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Save generated code to file
 */
export function saveAICode(
  code: string,
  outputPath: string
): void {
  // This would be called by the CLI
  // For now, just export the function
  // The actual file writing happens in the CLI command
}
