// AUTO-GENERATED by boardsmith build-ai
// Do not edit manually - regenerate with: npx boardsmith build-ai
//
// Training Statistics:
//   Games played: 1
//   Games completed: 1
//   Total states analyzed: 79
//   Candidate features: 22
//   Features selected: 15
//   Training iterations: 1
//   Estimated win rate vs random: 60.5%

import type { Game } from '@boardsmith/engine';
import type { Objective } from '@boardsmith/ai';
import type { CheckersGame } from './game.js';
import { CheckerPiece } from './elements.js';

/**
 * AI objectives for Checkers
 * These guide the MCTS bot to prefer better positions during playouts
 * 
 * Generated through self-play simulation and statistical analysis.
 * Higher weight = more important for winning.
 */
export function getCheckersObjectives(
  game: Game,
  playerIndex: number
): Record<string, Objective> {
  const checkersGame = game as CheckersGame;
  const player = checkersGame.players[playerIndex] as Player;
  const opponent = checkersGame.players[1 - playerIndex] as Player;

  return {
    // Player's CheckerPiece forwardDirection sum is higher than opponent
    // Correlation: +1.000
    'checkerpiece-forwardDirection-sum-advantage': {
      checker: () => {
        const myCount = checkersGame.all(Checkerpiece, { player }).filter(e => e.forwardDirection-sum).length;
        const theirCount = checkersGame.all(Checkerpiece, { player: opponent }).filter(e => e.forwardDirection-sum).length;
        return myCount > theirCount;
      },
      weight: 10,
    },

    // Player's CheckerPiece forwardDirection sum is at least 5
    // Correlation: +1.000
    'checkerpiece-forwardDirection-sum-gte-5': {
      checker: () => {
        const sum = checkersGame.all(Checkerpiece, { player }).reduce((s, e) => s + (e.forwardDirection ?? 0), 0);
        return sum >= 5;
      },
      weight: 10,
    },

    // Player has CheckerPiece with isKing
    // Correlation: +0.504
    'checkerpiece-has-isKing': {
      checker: () => checkersGame.all(Checkerpiece, { player }).some(e => e.isKing),
      weight: 5,
    },

    // Player has more CheckerPiece with isKing than opponent
    // Correlation: +0.504
    'checkerpiece-isKing-advantage': {
      checker: () => {
        const myCount = checkersGame.all(Checkerpiece, { player }).filter(e => e.isKing).length;
        const theirCount = checkersGame.all(Checkerpiece, { player: opponent }).filter(e => e.isKing).length;
        return myCount > theirCount;
      },
      weight: 5,
    },

    // Player's CheckerPiece forwardDirection sum is at least 10
    // Correlation: +0.407
    'checkerpiece-forwardDirection-sum-gte-10': {
      checker: () => {
        const sum = checkersGame.all(Checkerpiece, { player }).reduce((s, e) => s + (e.forwardDirection ?? 0), 0);
        return sum >= 10;
      },
      weight: 4.1,
    },

    // Player has at least 5 CheckerPiece
    // Correlation: +0.240
    'checkerpiece-count-gte-5': {
      checker: () => checkersGame.all(Checkerpiece, { player }).length >= 5,
      weight: 2.4,
    },

    // Player has fewer CheckerPiece than opponent
    // Correlation: -0.213
    'checkerpiece-count-disadvantage': {
      checker: () => {
        const myCount = checkersGame.all(Checkerpiece, { player }).length;
        const theirCount = checkersGame.all(Checkerpiece, { player: opponent }).length;
        return myCount < theirCount;
      },
      weight: -2.1,
    },

    // Player has strong majority (>66%) of CheckerPiece
    // Correlation: +0.191
    'checkerpiece-dominance': {
      checker: () => {
        const myCount = checkersGame.all(Checkerpiece, { player }).length;
        const total = checkersGame.all(Checkerpiece).length;
        return total > 0 && myCount > total * 0.66;
      },
      weight: 1.9,
    },

    // Player capturedCount is at least 5
    // Correlation: +0.189
    'player-capturedCount-gte-5': {
      checker: () => player.capturedCount >= 5,
      weight: 1.9,
    },

    // Player has more CheckerPiece than opponent
    // Correlation: +0.179
    'checkerpiece-count-advantage': {
      checker: () => {
        const myCount = checkersGame.all(Checkerpiece, { player }).length;
        const theirCount = checkersGame.all(Checkerpiece, { player: opponent }).length;
        return myCount > theirCount;
      },
      weight: 1.8,
    },

    // Player has higher capturedCount than opponent
    // Correlation: +0.179
    'player-capturedCount-lead': {
      checker: () => player.capturedCount > opponent.capturedCount,
      weight: 1.8,
    },

    // Player has majority (>50%) of CheckerPiece
    // Correlation: +0.179
    'checkerpiece-majority': {
      checker: () => {
        const myCount = checkersGame.all(Checkerpiece, { player }).length;
        const total = checkersGame.all(Checkerpiece).length;
        return total > 0 && myCount > total / 2;
      },
      weight: 1.8,
    },

    // Player has at least 3 CheckerPiece
    // Correlation: +0.167
    'checkerpiece-count-gte-3': {
      checker: () => checkersGame.all(Checkerpiece, { player }).length >= 3,
      weight: 1.7,
    },

    // Player capturedCount is at least 10
    // Correlation: +0.155
    'player-capturedCount-gte-10': {
      checker: () => player.capturedCount >= 10,
      weight: 1.6,
    },

    // Player capturedCount is very high (near win)
    // Correlation: +0.155
    'player-capturedCount-near-max': {
      checker: () => {
        const maxScore = Math.max(...checkersGame.players.map(p => p.capturedCount ?? 0));
        return maxScore > 0 && player.capturedCount >= maxScore * 0.75;
      },
      weight: 1.6,
    }

  };
}
