/**
 * Incremental training reads a game's existing `bot.ts` back in, blends the new
 * objectives with the old ones, and carries the cumulative counters forward.
 * These four functions are that path.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  parseExistingBot,
  parsedToLearned,
  mergeObjectives,
  getCumulativeStats,
  type ParsedObjective,
} from './bot-parser.js';
import type { LearnedObjective } from './types.js';

let dir: string;

const writeBot = (content: string): string => {
  const path = join(dir, 'bot.ts');
  writeFileSync(path, content, 'utf-8');
  return path;
};

const GENERATED_BOT = `/**
 * AUTO-GENERATED by boardsmith train
 * Games played: 500
 * Training iterations: 12
 * Final win rate: 63.5%
 */
export const bot = {
  objectives: {
    // Control the centre of the board
    'centre-control': { checker: (game, p) => game.centre(p) > 0, weight: 8.5 },
    // Hold more cards than the opponent
    'card-advantage': { checker: (game, p) => game.hand(p) > 3, weight: -2.5 },
  },
};
`;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'bs-bot-parser-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
  vi.restoreAllMocks();
});

describe('parseExistingBot', () => {
  it('returns null when the file does not exist', () => {
    expect(parseExistingBot(join(dir, 'missing.ts'))).toBeNull();
  });

  it('recognises a file boardsmith generated', () => {
    expect(parseExistingBot(writeBot(GENERATED_BOT))?.isAutoGenerated).toBe(true);
  });

  it('marks a hand-written file as not auto-generated', () => {
    const parsed = parseExistingBot(writeBot(`export const bot = { objectives: {} };`));
    expect(parsed?.isAutoGenerated).toBe(false);
  });

  it('extracts every objective with its id and weight', () => {
    const parsed = parseExistingBot(writeBot(GENERATED_BOT))!;
    expect(parsed.objectives.map((o) => [o.id, o.weight]))
      .toEqual([['centre-control', 8.5], ['card-advantage', -2.5]]);
  });

  it('keeps the checker source so it can be re-emitted unchanged', () => {
    const parsed = parseExistingBot(writeBot(GENERATED_BOT))!;
    expect(parsed.objectives[0].checkerCode).toContain('game.centre(p)');
  });

  it('picks up the description from the comment above the objective', () => {
    const parsed = parseExistingBot(writeBot(GENERATED_BOT))!;
    expect(parsed.objectives[0].description).toBe('Control the centre of the board');
  });

  it('falls back to the id when there is no description comment', () => {
    const parsed = parseExistingBot(writeBot(
      `export const bot = { objectives: { 'lone': { checker: (g, p) => true, weight: 1 } } };`
    ))!;
    expect(parsed.objectives[0].description).toBe('lone');
  });

  it('reads the cumulative training metadata', () => {
    const parsed = parseExistingBot(writeBot(GENERATED_BOT))!;
    expect(parsed.metadata).toEqual({ gamesPlayed: 500, iterations: 12, winRate: 0.635 });
  });

  it('reports no metadata at all when the file carries none', () => {
    const parsed = parseExistingBot(writeBot(
      `export const bot = { objectives: { 'x': { checker: (g, p) => true, weight: 1 } } };`
    ))!;
    expect(parsed.metadata).toBeUndefined();
  });

  it('returns an empty objective list for a file with none', () => {
    expect(parseExistingBot(writeBot('export const bot = {};'))!.objectives).toEqual([]);
  });

  it('warns and returns null rather than throwing when the path is unreadable', () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
    const asDirectory = join(dir, 'bot-dir');
    mkdirSync(asDirectory);
    expect(parseExistingBot(asDirectory)).toBeNull();
    expect(warn).toHaveBeenCalled();
  });
});

describe('parsedToLearned', () => {
  const parsed: ParsedObjective[] = [
    { id: 'a', description: 'A objective', weight: 4, checkerCode: '(g, p) => true' },
  ];

  it('maps the id onto the learned featureId', () => {
    expect(parsedToLearned(parsed)[0].featureId).toBe('a');
  });

  it('carries description, weight and checker across unchanged', () => {
    expect(parsedToLearned(parsed)[0]).toMatchObject({
      description: 'A objective',
      weight: 4,
      checkerCode: '(g, p) => true',
    });
  });

  it('marks the correlation unknown — a parsed file carries no statistics', () => {
    expect(parsedToLearned(parsed)[0].correlation).toBe(0);
  });

  it('preserves order and length', () => {
    const many = ['a', 'b', 'c'].map((id) => ({ ...parsed[0], id }));
    expect(parsedToLearned(many).map((o) => o.featureId)).toEqual(['a', 'b', 'c']);
  });

  it('handles an empty list', () => {
    expect(parsedToLearned([])).toEqual([]);
  });
});

describe('mergeObjectives', () => {
  const objective = (featureId: string, weight: number, correlation = 0.5): LearnedObjective => ({
    featureId,
    description: featureId,
    weight,
    checkerCode: '(g, p) => true',
    correlation,
  });

  const byId = (result: LearnedObjective[], id: string) =>
    result.find((o) => o.featureId === id)!;

  it('keeps an objective only the new training found', () => {
    const merged = mergeObjectives([], [objective('new', 5)]);
    expect(byId(merged, 'new').weight).toBe(5);
  });

  it('blends the weights of an objective found in both runs', () => {
    const merged = mergeObjectives([objective('a', 10)], [objective('a', 0)]);
    expect(byId(merged, 'a').weight).toBe(5);
  });

  it('honours an explicit blend ratio', () => {
    const merged = mergeObjectives([objective('a', 10)], [objective('a', 0)], { blendRatio: 1 });
    expect(byId(merged, 'a').weight).toBe(0);
    const keepsOld = mergeObjectives([objective('a', 10)], [objective('a', 0)], { blendRatio: 0 });
    expect(byId(keepsOld, 'a').weight).toBe(10);
  });

  it('rounds the blended weight to one decimal so generated code stays readable', () => {
    const merged = mergeObjectives([objective('a', 1)], [objective('a', 2)], { blendRatio: 1 / 3 });
    expect(byId(merged, 'a').weight).toBe(1.3);
  });

  it('takes the fresh correlation for a re-discovered objective', () => {
    const merged = mergeObjectives([objective('a', 5, 0.1)], [objective('a', 5, 0.9)]);
    expect(byId(merged, 'a').correlation).toBe(0.9);
  });

  it('decays an objective the new training did not re-discover', () => {
    const merged = mergeObjectives([objective('stale', 10)], []);
    expect(byId(merged, 'stale').weight).toBeCloseTo(8, 10);
  });

  it('honours an explicit decay factor', () => {
    const merged = mergeObjectives([objective('stale', 10)], [], { decayFactor: 0.5 });
    expect(byId(merged, 'stale').weight).toBe(5);
  });

  it('decays a negative weight toward zero, not away from it', () => {
    const merged = mergeObjectives([objective('stale', -10)], []);
    expect(byId(merged, 'stale').weight).toBeCloseTo(-8, 10);
  });

  it('sorts the result by weight magnitude, strongest first', () => {
    const merged = mergeObjectives([], [objective('small', 1), objective('big', -9)]);
    expect(merged.map((o) => o.featureId)).toEqual(['big', 'small']);
  });

  it('emits each objective exactly once', () => {
    const merged = mergeObjectives(
      [objective('a', 4), objective('b', 2)],
      [objective('a', 6), objective('c', 1)],
    );
    expect(merged.map((o) => o.featureId).sort()).toEqual(['a', 'b', 'c']);
  });

  it('does not mutate either input list', () => {
    const existing = [objective('a', 10)];
    const fresh = [objective('a', 0)];
    mergeObjectives(existing, fresh);
    expect(existing[0].weight).toBe(10);
    expect(fresh[0].weight).toBe(0);
  });

  it('returns nothing when both sides are empty', () => {
    expect(mergeObjectives([], [])).toEqual([]);
  });
});

describe('getCumulativeStats', () => {
  it('adds the new run onto the recorded totals', () => {
    expect(getCumulativeStats({ gamesPlayed: 500, iterations: 10 }, { gamesPlayed: 100, iterations: 2 }))
      .toEqual({ gamesPlayed: 600, iterations: 12 });
  });

  it('starts from zero when there is no prior metadata', () => {
    expect(getCumulativeStats(undefined, { gamesPlayed: 100, iterations: 2 }))
      .toEqual({ gamesPlayed: 100, iterations: 2 });
  });

  it('starts from zero for a partial metadata record', () => {
    expect(getCumulativeStats({ winRate: 0.6 }, { gamesPlayed: 100, iterations: 2 }))
      .toEqual({ gamesPlayed: 100, iterations: 2 });
  });

  it('accumulates across repeated runs', () => {
    let totals = getCumulativeStats(undefined, { gamesPlayed: 100, iterations: 1 });
    totals = getCumulativeStats(totals, { gamesPlayed: 100, iterations: 1 });
    expect(totals).toEqual({ gamesPlayed: 200, iterations: 2 });
  });
});
