/**
 * Weight evolution reads the weights of a game's bot.ts objectives with
 * `readObjectiveWeights` and writes the evolved ones back with
 * `updateBotWeights`. Both use one parser (#523), so an objective one can see
 * is one the other can: the round trip below holds them together. The write
 * must leave every other byte alone: hand-written checkers, imports, comments
 * and formatting all survive.
 */
import { describe, it, expect } from 'vitest';
import { readObjectiveWeights, updateBotWeights } from './objective-weights.js';
import type { ObjectiveWeight } from './types.js';

const objective = (id: string, weight: number): ObjectiveWeight => ({ id, weight });

const BOT_FILE = `/**
 * AUTO-GENERATED by boardsmith train
 */
import type { Game } from 'boardsmith';

export const bot = {
  objectives: {
    // Control the centre
    'centre-control': {
      checker: (game: Game, p: number) => {
        // a hand-written comment inside the checker
        return game.centre(p) > 0;
      },
      weight: 8.5,
    },
    'card-advantage': {
      checker: (game: Game, p: number) => game.hand(p) > 3,
      weight: -2.5, // was tuned by hand
    },
  },
};
`;

describe('updateBotWeights', () => {
  it('writes the new weight for a named objective', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 3.2)]);
    expect(updated).toContain('weight: 3.2,');
    expect(updated).not.toContain('weight: 8.5');
  });

  it('leaves objectives the update does not name untouched', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 3.2)]);
    expect(updated).toContain('weight: -2.5,');
  });

  it('updates several objectives in one pass', () => {
    const updated = updateBotWeights(BOT_FILE, [
      objective('centre-control', 1),
      objective('card-advantage', 2),
    ]);
    expect(updated).toContain('weight: 1,');
    expect(updated).toContain('weight: 2,');
  });

  it('writes a negative weight', () => {
    expect(updateBotWeights(BOT_FILE, [objective('centre-control', -4)]))
      .toContain('weight: -4,');
  });

  it('rounds to one decimal so the generated file stays readable', () => {
    expect(updateBotWeights(BOT_FILE, [objective('centre-control', 3.26789)]))
      .toContain('weight: 3.3,');
  });

  it('keeps the trailing comment on a weight line', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('card-advantage', 9)]);
    expect(updated).toContain('weight: 9, // was tuned by hand');
  });

  it('preserves the indentation of the line it rewrites', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    const line = updated.split('\n').find((l) => l.includes('weight: 1,'))!;
    expect(line.startsWith('      weight:')).toBe(true);
  });

  it('preserves the hand-written checker bodies verbatim', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    expect(updated).toContain('// a hand-written comment inside the checker');
    expect(updated).toContain('return game.centre(p) > 0;');
    expect(updated).toContain('game.hand(p) > 3');
  });

  it('preserves the imports and header comment', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    expect(updated).toContain("import type { Game } from 'boardsmith';");
    expect(updated).toContain('AUTO-GENERATED by boardsmith train');
  });

  it('returns the file unchanged when no objectives are supplied', () => {
    expect(updateBotWeights(BOT_FILE, [])).toBe(BOT_FILE);
  });

  it('refuses, naming it, an objective the file does not contain', () => {
    expect(() => updateBotWeights(BOT_FILE, [objective('not-in-file', 5)])).toThrow(/'not-in-file'/);
  });

  it('keeps the same number of lines — it rewrites, never reflows', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    expect(updated.split('\n')).toHaveLength(BOT_FILE.split('\n').length);
  });

  it('is idempotent — applying the same weights twice changes nothing further', () => {
    const once = updateBotWeights(BOT_FILE, [objective('centre-control', 3.2)]);
    expect(updateBotWeights(once, [objective('centre-control', 3.2)])).toBe(once);
  });

  describe('evolution metadata', () => {
    const stats = {
      generations: 5,
      population: 20,
      initialWinRate: 0.5,
      finalWinRate: 0.62,
    };

    it('is not written unless asked for', () => {
      expect(updateBotWeights(BOT_FILE, [objective('centre-control', 1)]))
        .not.toContain('Weight Evolution');
    });

    it('records the run when asked for', () => {
      const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)], {
        addMetadata: true,
        evolutionStats: stats,
      });
      expect(updated).toContain('Weight Evolution');
      expect(updated).toContain('Generations: 5');
      expect(updated).toContain('Population: 20');
    });

    it('reports the win rates and the improvement between them', () => {
      const updated = updateBotWeights(BOT_FILE, [], { addMetadata: true, evolutionStats: stats });
      expect(updated).toContain('Initial win rate: 50.0%');
      expect(updated).toContain('Final win rate: 62.0%');
      expect(updated).toContain('Improvement: 12.0%');
    });

    it('signs a regression rather than hiding it', () => {
      const updated = updateBotWeights(BOT_FILE, [], {
        addMetadata: true,
        evolutionStats: { ...stats, finalWinRate: 0.4 },
      });
      expect(updated).toContain('Improvement: -10.0%');
    });

    it('places the block above the imports', () => {
      const updated = updateBotWeights(BOT_FILE, [], { addMetadata: true, evolutionStats: stats });
      expect(updated.indexOf('Weight Evolution')).toBeLessThan(updated.indexOf('import '));
    });

    it('replaces a previous evolution block instead of stacking them up', () => {
      const once = updateBotWeights(BOT_FILE, [], { addMetadata: true, evolutionStats: stats });
      const twice = updateBotWeights(once, [], {
        addMetadata: true,
        evolutionStats: { ...stats, generations: 9 },
      });
      expect(twice.match(/Weight Evolution/g)).toHaveLength(1);
      expect(twice).toContain('Generations: 9');
    });

    it('does nothing when the flag is set but no stats are given', () => {
      const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)], {
        addMetadata: true,
      });
      expect(updated).not.toContain('Weight Evolution');
    });
  });
});

describe('readObjectiveWeights', () => {
  it('reads every objective with its id and weight, in source order', () => {
    expect(readObjectiveWeights(BOT_FILE)).toEqual([
      objective('centre-control', 8.5),
      objective('card-advantage', -2.5),
    ]);
  });

  it('reads ids written in either quote style or as identifiers', () => {
    const source = [
      'export const objectives = () => ({',
      '  "double-quoted": { checker: () => 1, weight: 1 },',
      "  'single-quoted': { checker: () => 1, weight: 2 },",
      '  plainName: { checker() { return 1; }, weight: 3 },',
      '  under_score: {',
      '    weight: 4,',
      '    checker: () => 1,',
      '  },',
      '});',
    ].join('\n');
    expect(readObjectiveWeights(source)).toEqual([
      objective('double-quoted', 1),
      objective('single-quoted', 2),
      objective('plainName', 3),
      objective('under_score', 4),
    ]);
  });

  it('does not take an object with no checker for an objective', () => {
    const source = "const settings = { 'not-an-objective': { weight: 5 } };";
    expect(readObjectiveWeights(source)).toEqual([]);
  });

  it('refuses, naming it, a weight that is not written as a number', () => {
    const source = "export const objectives = () => ({ 'computed': { checker: () => 1, weight: BASE * 2 } });";
    expect(() => readObjectiveWeights(source)).toThrow(/'computed'.*BASE \* 2/);
  });

  it('refuses an id two objectives share', () => {
    const source = [
      "const early = { 'lead': { checker: () => 1, weight: 1 } };",
      "const late = { 'lead': { checker: () => 1, weight: 2 } };",
    ].join('\n');
    expect(() => readObjectiveWeights(source)).toThrow(/'lead' more than once/);
  });
});

describe('reading and writing agree (#523)', () => {
  const SOURCES = {
    'the fixture bot': BOT_FILE,
    'ids and weights laid out every way bot.ts writes them': [
      'export function objectives(game: Game, seat: number): Record<string, Objective> {',
      '  return {',
      '    "double-quoted": { checker: () => 1, weight: 1 },',
      "    'Mixed_Case.id': {",
      '      checker: () => {',
      "        const nested = { weight: 99 }; // not an objective's weight",
      '        return nested.weight;',
      '      },',
      '      weight: -0.5, // trailing comment',
      '    },',
      '    plainName: { weight: 7, checker() { return 0; } },',
      '  };',
      '}',
    ].join('\n'),
  };

  for (const [name, source] of Object.entries(SOURCES)) {
    it(`writes back every weight it read, for ${name}`, () => {
      const read = readObjectiveWeights(source);
      expect(read.length).toBeGreaterThan(0);
      const changed = read.map((o, i) => objective(o.id, i + 10.5));

      const rewritten = updateBotWeights(source, changed);

      expect(readObjectiveWeights(rewritten)).toEqual(changed);
    });
  }
});
