/**
 * `updateBotWeights` is what weight evolution writes back: it rewrites the
 * weights in a game's existing bot.ts and must leave every other byte alone —
 * hand-written checkers, imports, comments and formatting all survive.
 */
import { describe, it, expect } from 'vitest';
import { updateBotWeights, DEFAULT_TRAINING_CONFIG } from './index.js';
import type { LearnedObjective } from './types.js';

const objective = (featureId: string, weight: number): LearnedObjective => ({
  featureId,
  description: featureId,
  weight,
  checkerCode: '(game, p) => true',
  correlation: 0.5,
});

const BOT_FILE = `/**
 * AUTO-GENERATED by boardsmith train
 */
import type { Game } from 'boardsmith';

export const bot = {
  objectives: {
    // Control the centre
    'centre-control': {
      checker: (game: Game, p: number) => {
        // a hand-written comment inside the checker
        return game.centre(p) > 0;
      },
      weight: 8.5,
    },
    'card-advantage': {
      checker: (game: Game, p: number) => game.hand(p) > 3,
      weight: -2.5, // was tuned by hand
    },
  },
};
`;

describe('updateBotWeights', () => {
  it('writes the new weight for a named objective', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 3.2)]);
    expect(updated).toContain('weight: 3.2,');
    expect(updated).not.toContain('weight: 8.5');
  });

  it('leaves objectives the update does not name untouched', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 3.2)]);
    expect(updated).toContain('weight: -2.5,');
  });

  it('updates several objectives in one pass', () => {
    const updated = updateBotWeights(BOT_FILE, [
      objective('centre-control', 1),
      objective('card-advantage', 2),
    ]);
    expect(updated).toContain('weight: 1,');
    expect(updated).toContain('weight: 2,');
  });

  it('writes a negative weight', () => {
    expect(updateBotWeights(BOT_FILE, [objective('centre-control', -4)]))
      .toContain('weight: -4,');
  });

  it('rounds to one decimal so the generated file stays readable', () => {
    expect(updateBotWeights(BOT_FILE, [objective('centre-control', 3.26789)]))
      .toContain('weight: 3.3,');
  });

  it('keeps the trailing comment on a weight line', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('card-advantage', 9)]);
    expect(updated).toContain('weight: 9, // was tuned by hand');
  });

  it('preserves the indentation of the line it rewrites', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    const line = updated.split('\n').find((l) => l.includes('weight: 1,'))!;
    expect(line.startsWith('      weight:')).toBe(true);
  });

  it('preserves the hand-written checker bodies verbatim', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    expect(updated).toContain('// a hand-written comment inside the checker');
    expect(updated).toContain('return game.centre(p) > 0;');
    expect(updated).toContain('game.hand(p) > 3');
  });

  it('preserves the imports and header comment', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    expect(updated).toContain("import type { Game } from 'boardsmith';");
    expect(updated).toContain('AUTO-GENERATED by boardsmith train');
  });

  it('returns the file unchanged when no objectives are supplied', () => {
    expect(updateBotWeights(BOT_FILE, [])).toBe(BOT_FILE);
  });

  it('ignores an objective the file does not contain', () => {
    expect(updateBotWeights(BOT_FILE, [objective('not-in-file', 5)])).toBe(BOT_FILE);
  });

  it('keeps the same number of lines — it rewrites, never reflows', () => {
    const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)]);
    expect(updated.split('\n')).toHaveLength(BOT_FILE.split('\n').length);
  });

  it('is idempotent — applying the same weights twice changes nothing further', () => {
    const once = updateBotWeights(BOT_FILE, [objective('centre-control', 3.2)]);
    expect(updateBotWeights(once, [objective('centre-control', 3.2)])).toBe(once);
  });

  describe('evolution metadata', () => {
    const stats = {
      generations: 5,
      population: 20,
      initialWinRate: 0.5,
      finalWinRate: 0.62,
    };

    it('is not written unless asked for', () => {
      expect(updateBotWeights(BOT_FILE, [objective('centre-control', 1)]))
        .not.toContain('Weight Evolution');
    });

    it('records the run when asked for', () => {
      const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)], {
        addMetadata: true,
        evolutionStats: stats,
      });
      expect(updated).toContain('Weight Evolution');
      expect(updated).toContain('Generations: 5');
      expect(updated).toContain('Population: 20');
    });

    it('reports the win rates and the improvement between them', () => {
      const updated = updateBotWeights(BOT_FILE, [], { addMetadata: true, evolutionStats: stats });
      expect(updated).toContain('Initial win rate: 50.0%');
      expect(updated).toContain('Final win rate: 62.0%');
      expect(updated).toContain('Improvement: 12.0%');
    });

    it('signs a regression rather than hiding it', () => {
      const updated = updateBotWeights(BOT_FILE, [], {
        addMetadata: true,
        evolutionStats: { ...stats, finalWinRate: 0.4 },
      });
      expect(updated).toContain('Improvement: -10.0%');
    });

    it('places the block above the imports', () => {
      const updated = updateBotWeights(BOT_FILE, [], { addMetadata: true, evolutionStats: stats });
      expect(updated.indexOf('Weight Evolution')).toBeLessThan(updated.indexOf('import '));
    });

    it('replaces a previous evolution block instead of stacking them up', () => {
      const once = updateBotWeights(BOT_FILE, [], { addMetadata: true, evolutionStats: stats });
      const twice = updateBotWeights(once, [], {
        addMetadata: true,
        evolutionStats: { ...stats, generations: 9 },
      });
      expect(twice.match(/Weight Evolution/g)).toHaveLength(1);
      expect(twice).toContain('Generations: 9');
    });

    it('does nothing when the flag is set but no stats are given', () => {
      const updated = updateBotWeights(BOT_FILE, [objective('centre-control', 1)], {
        addMetadata: true,
      });
      expect(updated).not.toContain('Weight Evolution');
    });
  });
});

describe('DEFAULT_TRAINING_CONFIG', () => {
  it('is a complete, runnable training configuration', () => {
    expect(DEFAULT_TRAINING_CONFIG).toEqual({
      gamesPerIteration: 100,
      iterations: 3,
      minCorrelation: 0.01,
      maxFeatures: 20,
      learnActions: true,
      gameTimeout: 60000,
      maxActionsPerGame: 300,
      oracleMCTSIterations: 50,
      trainedMCTSIterations: 10,
      benchmarkMCTSIterations: 100,
      evolve: false,
      evolutionGenerations: 5,
      evolutionMu: 5,
      evolutionLambda: 20,
      evolutionSigma: 1,
      evolutionBenchmarkGames: 50,
    });
  });

  it('bounds every run — no setting invites an unterminated training loop', () => {
    expect(DEFAULT_TRAINING_CONFIG.gamesPerIteration).toBeGreaterThan(0);
    expect(DEFAULT_TRAINING_CONFIG.iterations).toBeGreaterThan(0);
    expect(DEFAULT_TRAINING_CONFIG.gameTimeout).toBeGreaterThan(0);
    expect(DEFAULT_TRAINING_CONFIG.maxActionsPerGame).toBeGreaterThan(0);
  });

  it('keeps the correlation threshold a usable probability', () => {
    expect(DEFAULT_TRAINING_CONFIG.minCorrelation).toBeGreaterThan(0);
    expect(DEFAULT_TRAINING_CONFIG.minCorrelation).toBeLessThan(1);
  });

  it('spends more search on the oracle and the benchmark than on the trained bot', () => {
    // Training data quality and measurement accuracy are worth more iterations
    // than the trained bot needs, since its objectives already guide the search.
    expect(DEFAULT_TRAINING_CONFIG.oracleMCTSIterations!)
      .toBeGreaterThan(DEFAULT_TRAINING_CONFIG.trainedMCTSIterations!);
    expect(DEFAULT_TRAINING_CONFIG.benchmarkMCTSIterations!)
      .toBeGreaterThan(DEFAULT_TRAINING_CONFIG.oracleMCTSIterations!);
  });

  it('leaves evolution off by default — it is an explicit opt-in', () => {
    expect(DEFAULT_TRAINING_CONFIG.evolve).toBe(false);
  });

  it('describes a valid µ+λ population', () => {
    expect(DEFAULT_TRAINING_CONFIG.evolutionLambda!)
      .toBeGreaterThan(DEFAULT_TRAINING_CONFIG.evolutionMu!);
    expect(DEFAULT_TRAINING_CONFIG.evolutionMu!).toBeGreaterThan(0);
    expect(DEFAULT_TRAINING_CONFIG.evolutionSigma!).toBeGreaterThan(0);
    expect(DEFAULT_TRAINING_CONFIG.evolutionGenerations!).toBeGreaterThan(0);
  });

  it('carries no callbacks or seeds — those belong to a specific run', () => {
    expect(DEFAULT_TRAINING_CONFIG.onProgress).toBeUndefined();
    expect(DEFAULT_TRAINING_CONFIG.seed).toBeUndefined();
    expect(DEFAULT_TRAINING_CONFIG.existingBotPath).toBeUndefined();
  });
});
