// AUTO-GENERATED by boardsmith train-ai
// Do not edit manually - regenerate with: npx boardsmith train-ai
//
// Training Statistics:
//   Games played: 20
//   Games completed: 20
//   Total states analyzed: 646
//   Candidate features: 15
//   Features selected: 8
//   Training iterations: 1
//   Estimated win rate vs random: 50.0%

import type { Game } from '@boardsmith/engine';
import type { Objective } from '@boardsmith/ai';
import type { HexGame } from './game.js';

/**
 * AI objectives for Hex
 * These guide the MCTS bot to prefer better positions during playouts
 * 
 * Generated through self-play simulation and statistical analysis.
 * Higher weight = more important for winning.
 */
export function getHexObjectives(
  game: Game,
  playerIndex: number
): Record<string, Objective> {
  const hexGame = game as HexGame;
  const player = hexGame.players[playerIndex] as Player;
  const opponent = hexGame.players[1 - playerIndex] as Player;

  return {
    // Player needs fewer stones to complete winning path than opponent - KEY FEATURE
    // Correlation: -0.269
    'path-distance-advantage': {
      checker: () => {
        const myCount = hexGame.all(Path, { player }).filter(e => e.distance).length;
        const theirCount = hexGame.all(Path, { player: opponent }).filter(e => e.distance).length;
        return myCount > theirCount;
      },
      weight: -2.7,
    },

    // Player is within 3 stones of winning (path length <= 3)
    // Correlation: -0.220
    'near-win-within-3': {
      checker: () => {
        // Player is within 3 stones of winning (path length <= 3)
        // WARNING: Auto-generated fallback - always returns true
        // Implement game-specific logic for better AI performance
        return true;
      },
      weight: -2.2,
    },

    // Player is within 2 stones of winning (path length <= 2)
    // Correlation: -0.209
    'near-win-within-2': {
      checker: () => {
        // Player is within 2 stones of winning (path length <= 2)
        // WARNING: Auto-generated fallback - always returns true
        // Implement game-specific logic for better AI performance
        return true;
      },
      weight: -2.1,
    },

    // Player stonesPlaced is at least 5
    // Correlation: -0.162
    'player-stonesPlaced-gte-5': {
      checker: () => player.stonesPlaced >= 5,
      weight: -1.6,
    },

    // Player is within 1 stone of winning (path length <= 1)
    // Correlation: -0.134
    'near-win-within-1': {
      checker: () => {
        // Player is within 1 stone of winning (path length <= 1)
        // WARNING: Auto-generated fallback - always returns true
        // Implement game-specific logic for better AI performance
        return true;
      },
      weight: -1.3,
    },

    // Player stonesPlaced is at least 10
    // Correlation: -0.111
    'player-stonesPlaced-gte-10': {
      checker: () => player.stonesPlaced >= 10,
      weight: -1.1,
    },

    // Player stonesPlaced is very high (near win)
    // Correlation: -0.111
    'player-stonesPlaced-near-max': {
      checker: () => {
        const maxScore = Math.max(...hexGame.players.map(p => p.stonesPlaced ?? 0));
        return maxScore > 0 && player.stonesPlaced >= maxScore * 0.75;
      },
      weight: -1.1,
    },

    // Opponent's path is completely blocked (no route to goal) - nearly a win
    // Correlation: +0.101
    'opponent-path-blocked': {
      checker: () => hexGame.all(Opponent, { player }).some(e => e.path === 'blocked'),
      weight: 1,
    }

  };
}
