/**
 * `test-step-coverage.ts`: which game code a test file runs, test by test, for the mutation check of
 * a test that pins earlier behaviour (an exempt chunk's `none (regression)` row, #485).
 *
 * Such a test is mutation-tested on the game code it runs rather than on the chunk's own lines. To
 * know what it runs, the check runs it once with `COVERAGE_SETUP` as a vitest setup file. That file
 * asks V8 itself for block coverage through `node:inspector` (no coverage package is needed, and the
 * code under test is not changed): once after the test file has loaded, once between tests, and once
 * after each test, so each test's own share is known. It writes, for every module under the game's
 * `src/`, the ranges V8 counted and the module's text as vitest ran it. vitest (vite-node) runs a
 * module as one wrapped line followed by the transformed code and an inline source map, so
 * `readCoverage` maps each counted range back to positions in the file on disk.
 *
 * A position is "run" when the innermost range V8 reports around the generated code for it has a
 * count above zero. A position with no generated code of its own (no source-map segment on its line)
 * counts as run wherever any of its module ran, so the check never leaves out code a test might run.
 */
import { promises as fs, realpathSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/** The setup file the coverage run adds (see the file comment). Reads its settings from the environment. */
export const COVERAGE_SETUP = `// Generated by boardsmith test-step-check; removed when the check ends.
// Records the game code each test runs, with V8's own block coverage, for a test that pins earlier behaviour.
import { Session } from 'node:inspector';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { afterAll, afterEach, beforeAll, beforeEach, expect } from 'vitest';

const sourceDir = process.env.BOARDSMITH_COVERAGE_SRC;
const outFile = (testPath) => process.env.BOARDSMITH_COVERAGE + '/' + encodeURIComponent(testPath) + '.json';
const session = new Session();
session.connect();
const post = (method, params) =>
  new Promise((resolve, reject) => session.post(method, params, (error, result) => (error ? reject(error) : resolve(result))));
await post('Profiler.enable');
// Debugger is on only to read back each module's text; it must never stop at a \`debugger\` statement.
await post('Debugger.enable');
await post('Debugger.setSkipAllPauses', { skip: true });
await post('Profiler.startPreciseCoverage', { callCount: true, detailed: true });

const takes = [];
const scriptIds = new Map();
let testPath;
async function take(test) {
  const { result } = await post('Profiler.takePreciseCoverage');
  const modules = {};
  for (const script of result) {
    const path = script.url.startsWith('file://') ? fileURLToPath(script.url) : script.url;
    if (!path.startsWith(sourceDir) || path.includes('?')) continue;
    scriptIds.set(path, script.scriptId);
    modules[path] = script.functions.flatMap((f) => f.ranges.map((r) => [r.startOffset, r.endOffset, r.count]));
  }
  takes.push({ test, modules });
}
beforeAll(async () => {
  testPath = expect.getState().testPath;
  await take(null);
});
beforeEach(() => take(null));
afterEach((context) => take({ name: expect.getState().currentTestName, line: context.task.location?.line ?? null }));
afterAll(async () => {
  await take(null);
  const sources = {};
  for (const [path, scriptId] of scriptIds) sources[path] = (await post('Debugger.getScriptSource', { scriptId })).scriptSource;
  writeFileSync(outFile(testPath), JSON.stringify({ takes, sources }));
  session.disconnect();
});
`;

/** One counted range of generated code: `[start, end, count]`. */
export type Range = [number, number, number];

/** A test as the setup file names it: vitest's name for it (`describe > test`) and its line. */
interface CoveredTest {
  name: string;
  line: number | null;
}

/** What the setup file writes for one test file. A take with no test is loading or between tests. */
interface CoverageFile {
  takes: Array<{ test: CoveredTest | null; modules: Record<string, Range[]> }>;
  sources: Record<string, string>;
}

/** Whether a position ran, and which of the file's tests ran it. */
export interface PositionRuns {
  /** It ran at all: while loading, between tests, or in a test. */
  ran: boolean;
  /** Indexes into `FileCoverage.tests` of the tests that ran it. */
  tests: number[];
}

/** What one test file ran, module by module. */
export interface FileCoverage {
  /**
   * The tests the file ran, in order, each keyed as `testKeyOf` keys a test vitest reports, so the
   * two can be matched.
   */
  tests: string[];
  /** Project-relative paths of the game modules that ran at all, sorted. */
  modules: string[];
  /** Whether the code at `line` (1-based) and `column` (0-based) of `module` ran, and in which tests. */
  runs(module: string, line: number, column: number): PositionRuns;
}

/**
 * One key for a test, from its full name and line. vitest's JSON report joins a test's describe
 * titles and its own with spaces; the name a test sees while it runs joins them with ` > `.
 */
export const testKeyOf = (fullName: string, line: number | null | undefined) => `${line ?? '?'} ${fullName.replace(/ > /g, ' ')}`;

const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/** One source-map segment: generated column, original line (0-based) and original column. */
type Segment = [genColumn: number, line: number, column: number];

/** The fields of one source-map segment, each a base64 VLQ value. */
function decodeSegment(segmentText: string): number[] {
  const fields: number[] = [];
  let value = 0;
  let shift = 0;
  for (const char of segmentText) {
    const digit = BASE64.indexOf(char);
    if (digit < 0) throw new Error(`The source map vitest gave holds "${char}", which is not base64. This is a BoardSmith bug: file an issue.`);
    value += (digit & 31) << shift;
    if (digit & 32) {
      shift += 5;
      continue;
    }
    fields.push(value & 1 ? -(value >>> 1) : value >>> 1);
    value = 0;
    shift = 0;
  }
  return fields;
}

/**
 * The segments of a source map's `mappings`, by generated line (0-based). Segments with no original
 * position are dropped; the map's sources are taken as one file, the module itself.
 */
export function decodeMappings(mappings: string): Segment[][] {
  const lines: Segment[][] = [];
  const state = [0, 0, 0, 0, 0];
  for (const lineText of mappings.split(';')) {
    const segments: Segment[] = [];
    state[0] = 0;
    for (const segmentText of lineText.split(',')) {
      if (segmentText === '') continue;
      const fields = decodeSegment(segmentText);
      fields.forEach((delta, i) => (state[i] += delta));
      if (fields.length >= 4) segments.push([state[0], state[2], state[3]]);
    }
    lines.push(segments);
  }
  return lines;
}

/**
 * The count V8 gives each offset in `offsets` (sorted, ascending): that of the innermost range around
 * it, or 0 outside every range. V8's ranges nest, so one sweep with a stack of the ranges open at the
 * current offset finds each, in time proportional to the ranges and offsets rather than their product.
 */
export function countsAt(ranges: readonly Range[], offsets: readonly number[]): number[] {
  const sorted = [...ranges].sort((a, b) => a[0] - b[0] || b[1] - a[1]);
  const open: Range[] = [];
  const counts: number[] = [];
  let next = 0;
  for (const offset of offsets) {
    while (next < sorted.length && sorted[next][0] <= offset) {
      while (open.length > 0 && open[open.length - 1][1] <= sorted[next][0]) open.pop();
      open.push(sorted[next++]);
    }
    while (open.length > 0 && open[open.length - 1][1] <= offset) open.pop();
    counts.push(open.length > 0 ? open[open.length - 1][2] : 0);
  }
  return counts;
}

/** vite-node's wrapper around a module's code, all on the first line of what V8 runs. */
const VITE_NODE_WRAPPER = /^'use strict';async \([^)]*\)=>\{\{/;

/** For one module: by original line, each mapped position and which takes ran it. */
function moduleRuns(text: string, takes: CoverageFile['takes'], path: string): Map<number, Array<{ column: number; ran: boolean[] }>> {
  const map = /\/\/# sourceMappingURL=data:application\/json;[^,]*base64,([A-Za-z0-9+/=]+)\s*$/m.exec(text);
  const byLine = new Map<number, Array<{ column: number; ran: boolean[] }>>();
  if (!map) return byLine;
  const mappings = (JSON.parse(Buffer.from(map[1], 'base64').toString('utf-8')) as { mappings: string }).mappings;
  const wrapper = VITE_NODE_WRAPPER.exec(text)?.[0].length ?? 0;
  const lineStarts = [0];
  for (let i = 0; i < text.length; i++) if (text[i] === '\n') lineStarts.push(i + 1);
  const points: Array<{ offset: number; line: number; column: number }> = [];
  decodeMappings(mappings).forEach((segments, genLine) => {
    for (const [genColumn, line, column] of segments) {
      points.push({ offset: (lineStarts[genLine] ?? Infinity) + genColumn + (genLine === 0 ? wrapper : 0), line, column });
    }
  });
  points.sort((a, b) => a.offset - b.offset);
  const offsets = points.map((p) => p.offset);
  const ranByTake = takes.map((t) => (t.modules[path] ? countsAt(t.modules[path], offsets) : offsets.map(() => 0)));
  points.forEach(({ line, column }, i) => {
    const entries = byLine.get(line + 1) ?? [];
    entries.push({ column, ran: ranByTake.map((counts) => counts[i] > 0) });
    byLine.set(line + 1, entries);
  });
  for (const entries of byLine.values()) entries.sort((a, b) => a.column - b.column);
  return byLine;
}

/**
 * Reads what the coverage run wrote for one test file. `projectDir` is the project's real path, and
 * `testAbsPath` the test file's. Throws a readable error when the run wrote nothing for the file.
 */
export async function readCoverage(coverageDir: string, projectDir: string, testAbsPath: string, testPath: string): Promise<FileCoverage> {
  let file: CoverageFile;
  try {
    file = JSON.parse(await fs.readFile(join(coverageDir, `${encodeURIComponent(realpathSync(testAbsPath))}.json`), 'utf-8'));
  } catch {
    throw new Error(
      `The run that records which game code ${testPath} runs wrote nothing for it, so the mutation check cannot ` +
        "tell what that test pins. Run `boardsmith test` to see whether the file runs on its own, fix that, and run this check again.",
    );
  }
  const projectPath = (absPath: string) => relative(projectDir, absPath).split(sep).join('/');
  const testIndex = new Map<number, number>();
  const tests: string[] = [];
  file.takes.forEach((t, i) => {
    if (!t.test) return;
    testIndex.set(i, tests.length);
    tests.push(testKeyOf(t.test.name, t.test.line));
  });
  const ranAnywhere = new Map<string, boolean[]>();
  const positions = new Map<string, ReturnType<typeof moduleRuns>>();
  for (const [absPath, text] of Object.entries(file.sources)) {
    const anyRan = file.takes.map((t) => (t.modules[absPath] ?? []).some((r) => r[2] > 0));
    if (!anyRan.some(Boolean)) continue;
    ranAnywhere.set(projectPath(absPath), anyRan);
    positions.set(projectPath(absPath), moduleRuns(text, file.takes, absPath));
  }
  const summarise = (ran: boolean[]): PositionRuns => ({
    ran: ran.some(Boolean),
    tests: ran.flatMap((r, i) => (r && testIndex.has(i) ? [testIndex.get(i)!] : [])),
  });
  return {
    tests,
    modules: [...ranAnywhere.keys()].sort(),
    runs(module, line, column) {
      const entries = positions.get(module)?.get(line);
      if (!entries || entries.length === 0) return summarise(ranAnywhere.get(module) ?? []);
      const at = entries.filter((e) => e.column <= column).at(-1) ?? entries[0];
      return summarise(at.ran);
    },
  };
}

/** Where the setup file is told to write, and which modules count as the game's: settings for the coverage run. */
export function coverageEnv(coverageDir: string, projectDir: string): Record<string, string> {
  return { BOARDSMITH_COVERAGE: coverageDir, BOARDSMITH_COVERAGE_SRC: `${join(realpathSync(projectDir), 'src')}${sep}` };
}
